### PR TITLE
Bump rustfmt to 0.3.8

### PR DESCRIPTION
**Pull request by raskchanky**
This does for core what https://github.com/habitat-sh/habitat/pull/4936 did for the habitat repo.  Note that I did a tiny bit of refactoring in `install.rs` to break up one of the lines because `rustfmt` wouldn't format it due to the line length.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by baumanj** [comment]
Could you point out where exactly the refactoring in install.rs was? It's hard to see with all the automatic changes.

**Comment by raskchanky** [comment]
@baumanj https://github.com/habitat-sh/core/pull/23/files#diff-b9b27ac18067cb62ebad852e9abc0b10L337

**Comment by baumanj** [comment]
That refactor looks good, thought is appears travis is unhappy:
```
$ ./support/ci/lint.sh
   lint.sh: Checking for rustfmt
   lint.sh: Checking for version 0.3.8 of rustfmt
ERROR: `rustfmt' version 0.9.0-nightly doesn't match expected: 0.3.8
```

**Comment by raskchanky** [comment]
@baumanj Yeah I'm sorting that issue out on the builder repo too.

**Comment by baumanj** [comment]
It's not obvious to me what's going on there, but I noticed @reset pulled `support/ci/install_rustfmt.sh` out completely in his PR: https://github.com/habitat-sh/habitat/pull/4936/files#diff-cd13899bebe723020cd89ba4022b0b18

So, maybe that's worth trying?

**Pull request merged**
