### PR TITLE
Add http-client crate

### PR DESCRIPTION
**Pull request by christophermaier**
Part of habitat-sh/habitat#4726; see that for context.

Follow-on PRs for converting `habitat-sh/habitat` and `habitat-sh/builder` to use this will come next.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
ping @raskchanky @fnichol

**Comment by fnichol** [comment]
Is there the other side commit that removes this code from the habitat repo?

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by christophermaier** [comment]
@fnichol Not a PR yet, but I've already done the work on my laptop; once this merges, I'll push out the follow-on changes.

**Comment by fnichol** [comment]
Perfect, works for me!

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/core/builds/351453856).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/core/builds/351453856).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
