### PR TITLE
Uses tempfile instead of tempdir

### PR DESCRIPTION
**Pull request by rsertelon**
> Linked to #82 

cc @christophermaier 

Signed-off-by: Romain Sertelon <romain@sertelon.fr>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by rsertelon** [comment]
I'm wondering if the prefixes are really necessary here. Maybe for debug?

If we would not use them, code would be shorter ^^

**Comment by christophermaier** [comment]
tenor-125578438

**Comment by rsertelon** [comment]
Cool, I'll get to the ones in buidler and habitat then ;)

**Pull request merged**
